packages:
  - packages/*
  - packages/adapters/*
  - site
  - examples/*

catalogs:
  default:
    vite: npm:@voidzero-dev/vite-plus-core@0.2.7
    vite-plus: 0.2.7
    vitest: 4.1.10

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

allowBuilds:
  esbuild: true
  playwright: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
