type OperationType =
	| "@if group"
	| "@if"
	| "@else if"
	| "@else"
	| "@switch group"
	| "@case"
	| "@default"
	| "@for group"
	| "@for"
	| "@key"
	| "@await group"
	| "@await"
	| "@then"
	| "@loading group"
	| "@loading"
	| "@fallback"
	| "@try group"
	| "@try"
	| "@catch"
	| "@replace group"
	| "@replace"
	| "@html group"
	| "@html"
	| "@const"
	| "@console"
	| "@debugger"
	| "@function"
	| "@async function";

export default OperationType;
